name: Build and Push to ACR

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}

      # Login vào ACR
      - name: Docker login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_SHA=${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }}
          IMAGE_LATEST=${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest
          
          echo "IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV
          echo "IMAGE_LATEST=$IMAGE_LATEST" >> $GITHUB_ENV

          docker build -t $IMAGE_SHA -t $IMAGE_LATEST .
          
      # Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_SHA
          docker push $IMAGE_LATEST
